site_name: Percy Jackson
theme:
  name: material
  feature:
    - navigation.path
    - navigation.sections
    - navigation.expand
    - toc.follow
  font: 
    text: montserrat
    code: JetBrains Mono
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: teal
      accent: light blue
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: light blue
