services:
  api:
    platform: linux/amd64
    depends_on:
      db:
        condition: service_healthy
    build: 
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  db:
    image: postgres
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=percyJacksonMUD
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 15

volumes:
  db_data:
